// <auto-generated />
using System;
using DoctorAppointmentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorAppointmentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DoctorAppointmentAPI.Models.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Entity")
                        .HasColumnType("longtext");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("ReminderSent1Day")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReminderSent2Day")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReminderSentSameDay")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Degree")
                        .HasColumnType("longtext");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("longtext");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General & Primary Care",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(4498),
                            Name = "General Physician"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General & Primary Care",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5065),
                            Name = "Family Medicine Doctor"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General & Primary Care",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5066),
                            Name = "Internal Medicine Specialist"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Eye & ENT",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5067),
                            Name = "Ophthalmologist"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Eye & ENT",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5068),
                            Name = "Optometrist"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Eye & ENT",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5069),
                            Name = "ENT Specialist"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Bone & Physical",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5070),
                            Name = "Orthopedic Doctor"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Bone & Physical",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5071),
                            Name = "Physiotherapist"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Bone & Physical",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5072),
                            Name = "Rheumatologist"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Heart & Blood",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5072),
                            Name = "Cardiologist"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Heart & Blood",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5073),
                            Name = "Cardiac Surgeon"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Heart & Blood",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5074),
                            Name = "Hematologist"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Brain & Nerves",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5075),
                            Name = "Neurologist"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Brain & Nerves",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5076),
                            Name = "Neurosurgeon"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Brain & Nerves",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5077),
                            Name = "Psychiatrist"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Brain & Nerves",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5077),
                            Name = "Psychologist"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Women & Child Care",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5088),
                            Name = "Gynecologist"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Women & Child Care",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5089),
                            Name = "Obstetrician"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Women & Child Care",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5090),
                            Name = "Pediatrician"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Women & Child Care",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5091),
                            Name = "Neonatologist"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Lungs & Breathing",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5092),
                            Name = "Pulmonologist"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Lungs & Breathing",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5093),
                            Name = "Respiratory Therapist"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Digestive System",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5093),
                            Name = "Gastroenterologist"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Digestive System",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5094),
                            Name = "Hepatologist"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Skin & Beauty",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5095),
                            Name = "Dermatologist"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Skin & Beauty",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5096),
                            Name = "Cosmetologist"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Dental",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5097),
                            Name = "Dentist"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Dental",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5098),
                            Name = "Orthodontist"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Dental",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5098),
                            Name = "Oral Surgeon"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Specialized Fields",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5099),
                            Name = "Oncologist"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Specialized Fields",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5100),
                            Name = "Endocrinologist"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Specialized Fields",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5101),
                            Name = "Nephrologist"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Specialized Fields",
                            CreatedAt = new DateTime(2026, 4, 9, 6, 22, 33, 188, DateTimeKind.Utc).AddTicks(5102),
                            Name = "Urologist"
                        });
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EmailVerifyToken")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Appointment", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoctorAppointmentAPI.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoctorAppointmentAPI.Models.Specialization", "Specialization")
                        .WithMany("Appointments")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Doctor", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorAppointmentAPI.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("DoctorAppointmentAPI.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Patient", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("DoctorAppointmentAPI.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Session", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Specialization", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
